{{ if .Values.cronjob.enabled }}
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ .Values.db_cleaner }}
spec:
  schedule: {{ .Values.cronjob.schedule }}
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: mongocleaner
              image: {{ .Values.cronjob.image }}
              imagePullPolicy: "IfNotPresent"
              command :
              - "mongosh"
              - "$(MONGO_DB)"
              - "--host" 
              - "mongo-mongodb-0.mongo-mongodb-headless.default.svc.cluster.local:27017"
              - "--eval"
              - "db.dropDatabase()"
              - "--authenticationDatabase" 
              - "admin"
              - "-u"
              - "$(MONGO_USERNAME)"
              - "-p"
              - "$(MONGO_PASSWORD)"
              envFrom:
              - secretRef:
                  name: {{ .Values.cronjob.cleaner_secret }}
          restartPolicy: OnFailure
{{ end }}