apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ ternary "ClusterIP" "LoadBalancer" .Values.ingress.enabled }}
  selector:
    app: {{ .Values.service.app }}
  ports:
    - protocol: {{ .Values.service.protocol }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort}}